# Generated by Django 3.0.3 on 2020-02-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='oservacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
