# Generated by Django 3.0.3 on 2020-02-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20200211_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='oservacao',
            new_name='observacao',
        ),
    ]
